requires 'perl', '5.020';

requires 'Moo', '2.000';
requires 'Types::Standard', '1.000';
requires 'List::Util', '1.33';
requires 'POSIX';
requires 'JSON::XS';

on 'test' => sub {
    requires 'Test::More', '0.98';
    requires 'Test::Exception';
};
