use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.007006
use Test::Spelling 0.17;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib ) );
__DATA__
Astrophysical
Axis
AxisFormat
AxisLabel
AxisMinorTics
AxisRange
AxisTics
Base
Bound
CXC
Clone
Color
ColorSpec
CoordOffset2D
CoordOffset3D
CoordPosition2D
CoordPosition3D
CoordValue
Diab
Font
Gnuplot
Jerius
Key
Label
LiteralDataValue
Margin
Margins
MultiPlot
Numeric
Observatory
Range
Role
Smithsonian
TermOptions
Terminal
TerminalBase
TimeDate
Timestamp
Title
Types
Util
V0
V1
cairo
djerius
lib
pdfcairo
pngcairo
