---
abstract: 'Extensible, framework-agnostic base specification layer for multi-part file uploads'
author:
  - 'Joshua S. Day <HAX@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Exception: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150013'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Uniform-Upload
no_index:
  directory:
    - t
    - inc
requires:
  Uniform::Exceptions: '1.00'
  Uniform::Utils: '1.01'
  perl: '5.010000'
resources:
  bugtracker: https://github.com/haxmeister/perl-Uniform-Upload/issues
  repository: https://github.com/haxmeister/perl-Uniform-Upload
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
