---
abstract: 'an implementation of the Uratani-Takeda string searching algorithm'
author:
  - 'Robert Rothenberg <perl@rhizomnic.com>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Metadata: '0'
  Test2::Tools::Compare: '0'
  Test2::Tools::Exception: '0'
  Test2::V0: '0'
  Test::More: '0'
  experimental: '0'
  strict: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.037, CPAN::Meta::Converter version 2.150014'
keywords:
  - Aho-Corasick
  - Boyer-Moore
  - Commentz-Walter
  - Uratani-Takeda
  - algorithm
  - multi-term
  - multiple
  - patterns
  - pattern
  - matching
  - string
  - matching
  - string
  - searching
  - text-search
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Algorithm-UrataniTakeda
provides:
  Algorithm::UrataniTakeda:
    file: lib/Algorithm/UrataniTakeda.pm
    version: v0.1.6
requires:
  Carp: '0'
  List::Util: '0'
  Object::Pad: '0.59'
  integer: '0'
  perl: v5.26.0
  warnings: '0'
resources:
  bugtracker: https://github.com/robrwo/perl-Algorithm-UrataniTakeda/issues
  repository: git://github.com/robrwo/perl-Algorithm-UrataniTakeda.git
version: v0.1.6
x_authority: cpan:RRWO
x_generated_by_perl: v5.42.1
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: Artistic-2.0
x_static_install: 1
