---
abstract: 'Offline URL helpers for iptv-org pro'
author:
  - bbwdadfg
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IPTV-Org-Pro-URLTools
no_index:
  directory:
    - t
    - inc
resources:
  homepage: https://iptv-org.pro/
  repository: https://github.com/bbwdadfg/iptv-org-pro-url-tools
version: v0.2.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
