requires 'perl'           => '5.020';
requires 'Alien::Libgit2' => '0.002';
requires 'Carp';
requires 'Exporter';
requires 'FFI::Platypus'  => '2.00';

on test => sub {
  requires 'Path::Tiny';
  requires 'Test2::V0';
};
