name    = CXC-Gnuplot
author  = Diab Jerius <djerius@cfa.harvard.edu>
license = GPL_3
copyright_holder = Smithsonian Astrophysical Observatory
copyright_year   = 2024

[@Starter]
revision = 5
installer = ModuleBuildTiny
managed_versions = 1
-remove = GatherDir
regenerate = META.json
regenerate = LICENSE
regenerate = Build.PL
regenerate = CONTRIBUTING.md
regenerate = README
regenerate = README.md

[if / inject/cpan-mirror-tiny ]
dz_plugin = Run::Release
dz_plugin_name = darkpan/cpan-mirror-tiny
?= defined $ENV{PERL_CPAN_MIRROR_TINY_BASE}
?= do { require File::Which; File::Which::which( 'cpan-mirror-tiny' ) }
>= run_no_trial = cpan-mirror-tiny inject %a
>= run_no_trial = cpan-mirror-tiny gen-index

[Encoding / ignore]
encoding = bytes
filename = GPATH
filename = GRTAGS
filename = GTAGS

[GatherDir]
exclude_filename = share/shared-files.tar.gz
exclude_filename = LICENSE
exclude_filename = Build.PL
exclude_filename = CONTRIBUTING.md
exclude_filename = pod2htmd.tmp
exclude_filename = html-it
exclude_filename = README
exclude_filename = README.md
prune_directory = local
prune_directory = dev
exclude_match = [#~]$
exclude_match = ^META[.].*
exclude_match = GTAGS|GRTAGS|GPATH

[GatherDir::Template]
root = templates

[ReadmeAnyFromPod]
filename = README.md
type = markdown

[PodWeaver]
replacer = replace_with_blank
post_code_replacer = replace_with_nothing

[InsertExample]
remove_boiler = 1

[InsertCopyright]

[MetaResources]
bugtracker.web = https://rt.cpan.org/Public/Dist/Display.html?Name=CXC-Gnuplot
bugtracker.mailto = bug-cxc-gnuplot@rt.cpan.org
repository.web = https://codeberg.org/CXC-Optics/p5-CXC-Gnuplot
repository.url = https://codeberg.org/CXC-Optics/p5-CXC-Gnuplot.git
repository.type = git

[CheckMetaResources]

[MetaNoIndex]
directory = t
directory = xt
directory = inc
directory = share
directory = eg
directory = examples

[Regenerate]
filenames = META.json
filenames = LICENSE
filenames = Build.PL
filenames = CONTRIBUTING.md

[Test::Compile]
[Test::NoTabs]
[Test::Fixme]
[Test::Version]
[Test::NoBreakpoints]
[Test::TrailingSpace]
[Test::DistManifest]
[Test::CPAN::Changes]
[Test::CPAN::Meta::JSON]
[Test::Perl::Critic]
critic_config = perlcritic.rc

[Test::CleanNamespaces]
skip = ::Types$
skip = ::Util$

[Test::PodSpelling]

[PodCoverageTests]

[Prereqs::AuthorDeps]
[EnsurePrereqsInstalled]

[EnsureChangesHasContent]

; --- Project-specific directives

; [AutoPrereqs]

[Prereqs]
CXC::Data::Visitor       = 0
Exporter::Shiny          = 0
Feature::Compat::Class   = 0.08
File::ShareDir::Tarball  = 0
Hash::Merge              = 0
Import::Into             = 0
Lexical::Import          = 0
Path::Tiny               = 0
Ref::Util                = 0
Regexp::Common           = 0
Syntax::Operator::Elem   = 0
Text::Balanced           = 0
Type::Library            = 2.008003
builtin::compat          = 0.003003
experimental             = 0
namespace::clean         = 0

[Prereqs / ConfigureRequires ]
Module::Build::Tiny      = 0

[Prereqs / TestRequires]
Test2::Tools::TypeTiny   = 0.93.1
Test2::V0                = 0
Test::File::ShareDir     = 0
Test::Lib                = 0

; authordep Pod::Weaver::Plugin::StopWords
; authordep Pod::Weaver::Section::Contributors
; authordep Pod::Weaver::Section::GenerateSection
; authordep Pod::Weaver::Section::SeeAlso

[Prereqs / DevelopRequires ]
Pod::Coverage::TrustPod  = 0
Test::CPAN::Changes      = 0
Test::CPAN::Meta::JSON   = 0
Test::CleanNamespaces    = 0
Test::DistManifest       = 0
Test::More               = 0
Test::NoBreakpoints      = 0
Test::NoTabs             = 0
Test::Pod                = 0
Test::Pod::Coverage      = 0
Test::Version            = 0
