---
abstract: 'HTTP client that impersonates a browser TLS/HTTP2 fingerprint'
author:
  - vividsnow
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  Alien::Base::Wrapper: '1.97'
  Alien::curlimpersonate: '0.02'
  ExtUtils::MakeMaker: '6.52'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150013'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Curl-Impersonate
no_index:
  directory:
    - t
    - inc
provides:
  Curl::Impersonate:
    file: lib/Curl/Impersonate.pm
    version: '0.01'
  Curl::Impersonate::Multi:
    file: lib/Curl/Impersonate.pm
requires:
  perl: '5.010'
resources:
  bugtracker: https://github.com/vividsnow/perl5-curl-impersonate/issues
  repository: https://github.com/vividsnow/perl5-curl-impersonate.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
