---
abstract: 'Extracts structured fields from log records using YAML rule files.'
author:
  - 'Zane C. Bowers-Hadley <vvelox@vvelox.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Log-Munger
no_index:
  directory:
    - t
    - inc
recommends:
  IP::Geolocation::MMDB: '0'
requires:
  Algorithm::Dependency::Ordered: '0'
  Algorithm::Dependency::Source::HoA: '0'
  App::Cmd: '0'
  File::ShareDir: '0'
  File::Slurp: '0'
  Hash::Merge: '0'
  JSON: '0'
  Template: '0'
  YAML::XS: '0'
  perl: '5.006'
resources:
  repository: https://github.com/LilithSec/Log-Munger
version: v0.0.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
