use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.007006
use Test::Spelling 0.17;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib ) );
__DATA__
109326
Aaron
Alders
Alders'
Client
Endpoint
Johnson
Lamere
OAuth
Olaf
Response
Spotify
WWW
aaronjjohnson
aj
audiobook
audiobooks
autocheck
lib
modularised
olaf
playlist
trs
ua
