name    = Typesense-Client
author  = SeHarrys <hdelgado@cpan.org>
license = Artistic_2_0
copyright_holder = SeHarrys
version = 0.001

[@Starter]
-remove = MakeMaker
[MakeMaker]
eumm_version = 7.62
[PkgVersion]

; the local docker test environment is not part of the release
[PruneFiles]
match = ^dev/
[NextRelease]
[ReadmeAnyFromPod]
type     = markdown
filename = README.md
location = root

[MetaResources]
repository.web  = https://github.com/SeHarrys/typesense-client-perl
repository.url  = https://github.com/SeHarrys/typesense-client-perl.git
repository.type = git
bugtracker.web  = https://github.com/SeHarrys/typesense-client-perl/issues

[Prereqs]
perl         = 5.038
Object::Pad  = 0.808
Mojolicious  = 9.0
Digest::SHA  = 0
MIME::Base64 = 0

[Prereqs / TestRequires]
Test::More     = 1.302
Test::Warnings = 0.031
